Update dex-scrapper-python-package.yml

diff --git a/.github/workflows/dex-scrapper-python-package.yml b/.github/workflows/dex-scrapper-python-package.yml
--- a/.github/workflows/dex-scrapper-python-package.yml
+++ b/.github/workflows/dex-scrapper-python-package.yml
@@ -18,7 +18,6 @@ jobs:
       uses: actions/setup-python@v5
       with:
         python-version: 3.13
-
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip wheel setuptools
@@ -41,3 +40,20 @@ jobs:
       run: |
         python dexscraper/a.py
       # python dexscraper/webscraper.py "${{ github.event.inputs.scraper_param }}"
+    - name: Check if image exists
+        run: |
+          if [ ! -f ./downloaded/screen.png ]; then
+            echo "Image not found: ./downloaded/screen.png"
+            exit 1
+          fi
+
+      # Étape pour envoyer l'image via l'API Telegram
+      - name: Send image to Telegram
+        env:
+          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
+          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
+        run: |
+          curl -X POST "https://api.telegram.org/bot7919513232:AAGY0BRtwdyflFilVYH3QXWWjReazvH1jj8/sendPhoto" \
+               -F chat_id="7491475542" \
+               -F photo="@./downloaded/screen.png" \
+               -F caption="Voici l'image envoyée depuis GitHub Actions !"
